# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Profile(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Vyhod = QtWidgets.QPushButton(self.centralwidget)
        self.Vyhod.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.Vyhod.setObjectName("Vyhod")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 139, 99))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Name_profile = QtWidgets.QLabel(self.widget)
        self.Name_profile.setObjectName("Name_profile")
        self.gridLayout.addWidget(self.Name_profile, 0, 0, 1, 1)
        self.Name_profile_2 = QtWidgets.QLineEdit(self.widget)
        self.Name_profile_2.setObjectName("Name_profile_2")
        self.gridLayout.addWidget(self.Name_profile_2, 1, 0, 1, 1)
        self.Email_profile = QtWidgets.QLabel(self.widget)
        self.Email_profile.setObjectName("Email_profile")
        self.gridLayout.addWidget(self.Email_profile, 2, 0, 1, 1)
        self.Email_profile_2 = QtWidgets.QLineEdit(self.widget)
        self.Email_profile_2.setObjectName("Email_profile_2")
        self.gridLayout.addWidget(self.Email_profile_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Vyhod.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Профиль"))
        self.Name_profile.setText(_translate("MainWindow", "Почта"))
        self.Email_profile.setText(_translate("MainWindow", "Пароль"))

